services:
  db:
    image: postgres:16-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py wait_for_db &&
        celery -A library_project worker -B -l info
      "
    depends_on:
      - db
      - redis

  bot:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python -m telegram_bot.bot
      "
    depends_on:
      - db
      - redis
      - web

volumes:
  my_db:
